#!/usr/bin/env bash
set -a
source /usr/share/yunohost/helpers

app="${0//.\/50-}"
username=$1
mail=$2

final_path=$(ynh_app_setting_get --app=$app --key=final_path)

pushd $final_path/backend
	sudo -u $app $final_path/bin/librephotos-cli shell <<< "
from django.contrib.auth import get_user_model
User = get_user_model()
try:
    user = User.objects.get(username='$user')
    user.scan_directory='/home/yunohost.multimedia/$user/Picture'
    user.save()
except User.DoesNotExist:
    User.objects.create_user('$username', email='$mail', scan_directory='/home/yunohost.multimedia/$user/Picture')
" 2>&1
popd
