#!/usr/bin/env bash
set -a
source /usr/share/yunohost/helpers

app="${0//50-}"
username=$1
purge=$2

final_path=$(ynh_app_setting_get --app=$app --key=final_path)

pushd $final_path/backend
	source $final_path/backend/venv/bin/activate
	$final_path/bin/librephotos-cli shell <<< "
from django.contrib.auth import get_user_model
User = get_user_model()
try:
    user = User.objects.get(username='$user')
    user.is_active = False
    user.save()
    if $purge:
        user.delete()
except User.DoesNotExist:
    pass
"
popd
