#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers


#FIXME: Might not be required
path="/"

#=================================================
# STANDARD MODIFICATIONS
#=================================================

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=5

unpack_source

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
# SET UP BACKEND
#=================================================
ynh_script_progression --message="Setting up backend..." --weight=60

set_up_backend

#=================================================
# SET UP FRONTEND
#=================================================
ynh_script_progression --message="Setting up frontend..." --weight=15

set_up_frontend

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring systemd services..." --weight=1

# Create dedicated systemd configs
ynh_add_systemd_config --service="$app-backend"          --template=backend.service
ynh_add_systemd_config --service="$app-frontend"         --template=frontend.service
ynh_add_systemd_config --service="$app-image-similarity" --template=image-similarity.service
ynh_add_systemd_config --service="$app-worker"           --template=worker.service

#=================================================
# ADD CONFIGURATIONS
#=================================================
ynh_script_progression --message="Generating configuration files..." --weight=1

add_configurations

#=================================================
# FINALIZE DATABASE
#=================================================
ynh_script_progression --message="Finalizing database..." --weight=1

upgrade_db

pushd "$install_dir/backend"
    admin_mail="$(ynh_user_get_info $admin 'mail')"
    sudo -u $app bash -c "
        set -a
        export PATH=\"$path_prefix:"'$PATH'"\"
        source \"$install_dir\"/librephotos.env
        python3 manage.py createsuperuser --noinput --username \"$admin\" --email \"$admin_mail\"
    " 2>&1
    for user in $(ynh_user_list); do
        mail=$(ynh_user_get_info --username="$user" --key=mail)
        sudo -u $app bash -c "
            set -a
            export PATH=\"$path_prefix:"'$PATH'"\"
            source \"$install_dir\"/librephotos.env
            python3 manage.py shell
        " <<< "
from django.contrib.auth import get_user_model
User = get_user_model()
try:
    user = User.objects.get(username='$user')
    user.scan_directory='/home/yunohost.multimedia/$user/Picture'
    user.save()
except User.DoesNotExist:
    User.objects.create_user('$user', email='$mail', scan_directory='/home/yunohost.multimedia/$user/Picture')
" 2>&1
    done
popd

#=================================================
# YUNOHOST MULTIMEDIA INTEGRATION
#=================================================
ynh_script_progression --message="Adding multimedia directories..." --weight=1

# Build YunoHost multimedia directories
ynh_multimedia_build_main_dir
if [ "$allow_multimedia_write" -eq 1 ]; then
    ynh_multimedia_addaccess $app
fi

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions to app files
set_permissions

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Configuring log rotation..." --weight=1

# Use logrotate to manage application logfiles
set_up_logrotate

#=================================================
# INTEGRATE SERVICES IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating services in YunoHost..." --weight=1

yunohost service add $app-backend --description="Backend for librephotos" --log="/var/log/$app/gunicorn_django.log"
yunohost service add $app-frontend --description="Frontend for librephotos" --log="/var/log/$app/$app-frontend.log"
yunohost service add $app-image-similarity --description="Image similarity server for librephotos" --log="/var/log/$app/image_similarity.log"
yunohost service add $app-worker --description="Worker for librephotos" --log="/var/log/$app/$app-worker.log"

#=================================================
# START SYSTEMD SERVICES
#=================================================
ynh_script_progression --message="Starting systemd services..." --weight=1

# Start systemd services
ynh_systemd_action --service_name=$app-backend --action="start" --log_path="/var/log/$app/gunicorn_django.log" --line_match="Listening at: http"
ynh_systemd_action --service_name=$app-frontend --action="start" --log_path="systemd" --line_match="INFO: Accepting connections at http:"
ynh_systemd_action --service_name=$app-image-similarity --action="start" --log_path="/var/log/$app/image_similarity.log"
ynh_systemd_action --service_name=$app-worker --action="start" --log_path="/var/log/$app/$app-worker.log"


#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
