#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

ynh_script_progression --message="Removing $app services integration..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
yunohost service remove $app-backend
yunohost service remove $app-frontend
yunohost service remove $app-image-similarity
yunohost service remove $app-worker
#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Stopping and removing the systemd service..." --weight=10

# Remove the dedicated systemd config
ynh_remove_systemd_config --service="$app-backend"
ynh_remove_systemd_config --service="$app-frontend"
ynh_remove_systemd_config --service="$app-image-similarity"
ynh_remove_systemd_config --service="$app-worker"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..." --weight=1

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression --message="Removing logrotate configuration..." --weight=1

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# REMOVE NODE
#=================================================
ynh_script_progression --message="Removing Node.js..." --weight=1

ynh_remove_nodejs

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE VARIOUS FILES
#=================================================

# Remove the log files
ynh_secure_remove --file="/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Removal of $app completed" --last
